# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'IntelligentLock' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for IntelligentLock
  pod 'CocoaAsyncSocket', '~> 7.6.3'
  pod 'AFNetworking', '~> 3.2.1'
  pod 'NullSafe', '~> 1.2.3'
  pod 'SVProgressHUD', '~> 2.2.5'

  target 'IntelligentLockTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'IntelligentLockUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
